### ISSUE TITLE
File selector directive: optimize layout, show real file name

### ISSUE THREAD

**Issue by rolandschaub** [zephir/luya#533]
Current look:

<img width="774" alt="file selector aktuell" src="https://cloud.githubusercontent.com/assets/3786245/11116530/8488b60c-8933-11e5-8021-a0fabc491fc6.png">

Optimized look:

![file selector optimiert](https://cloud.githubusercontent.com/assets/3786245/11116539/8a7fccbc-8933-11e5-9a62-0ec190095b9f.png)

Instead of the storage path, the real and **original** file name should be displayed.

**Comment by nadar** [comment]
input replaced with span ng-bind and added the original file name instead of the path. Please change the fileupload__path class to @rolandschaub design proposal:

@TheMaaarc when your closing this issue please **DO NOT FORGE TO ADD CHANGELOG.MD**. thanks.

![image](https://cloud.githubusercontent.com/assets/3417221/11118236/a21af65a-8940-11e5-93eb-571dd1b2bff5.png)
